from bs4 import BeautifulSoup

# Open a html file manually downloaded from the url generated by main.py for reading
# encoding = 'utf-8' is a type of variable-length character encoding standard used for webs
with open('assets/bookingdotcom_philadelphia.html', 'r', encoding='utf-8') as f:

    # read the entire contents of the html file
    contents = f.read()

    soup = BeautifulSoup(contents, "html.parser")

    # create a new text file for writing
    with open('hotel_titles.txt', 'w', encoding='utf-8') as file:

        # Find all elements with tag 'div' and attribute data-testtid = 'title'
        for div in soup.find_all('div', {'data-testid': 'title'}):
            print(div.text)
            # write the only text content (no tag) of the div element to a separate file.
            file.write(str(div.text) + '\n')