from bs4 import BeautifulSoup

# Open a html file manually downloaded from the url generated by main.py for reading
# encoding = 'utf-8' is a type of variable-length character encoding standard used for webs
with open('assets/bookingdotcom_philadelphia.html', 'r', encoding='utf-8') as f:

    # read the entire contents of the html file
    contents = f.read()

    soup = BeautifulSoup(contents, "html.parser")

    # Hotel Name Getter
    print("Hotels:")
    # create a new text file for writing
    with open('hotel_titles.txt', 'w', encoding='utf-8') as file:

        # Find all elements with tag 'div' and attribute data-testtid = 'title'
        for div in soup.find_all('div', {'data-testid': 'title'}):
            print(div.text)
            # write the only text content (no tag) of the div element to a separate file.
            file.write(str(div.text) + '\n')

    # Hotel Rating Getter
    print("Hotel Ratings: ")
    with open('hotel_ratings.txt', 'w', encoding='utf-8') as file:

        # Find all elements with tag 'div' and attribute class = 'a3b8729ab1 d86cee9b25'
        # a3b8729ab1 d86cee9b25 is a web specific code for numerical hotel ratings
        for div in soup.find_all('div', {'class': 'a3b8729ab1 d86cee9b25'}):
            print(div.text[0:3])
            file.write(str(div.text[0:3]) + '\n')

    
    # Get each hotel's property card contents from HTML
    with open('hotels.txt', 'w', encoding='utf-8') as file:
        # each hotel property card container has attribute data-testid = 'property-card-container'
        for container in soup.find_all('div', {'data-testid': 'property-card-container'}):
            file.write(str(container) + '\n\n')

            title = container.find('div', {'data-testid': 'title'}).text
            rating = container.find('div', {'class': 'a3b8729ab1 d86cee9b25'}).text[0:3]

            print(title + '\t' + rating)
